// Package server is the desktop gateway's thin read + config API
// (design/desktop.md §10.2). It exposes:
//   - recording data captured by the data plane (request logs, session
//     aggregation, trace payloads, per-agent overview) for the UI; and
//   - CRUD over providers/models/routes backed by the local YAML file
//     (design/desktop.md §7), with hot-reload via DispatcherWatcher.Build.
//
// It reuses the query semantics of internal/admin's /request-logs and /trace/*
// endpoints and mirrors the CRUD shape of /providers /models /routes, but is
// written against the SQLite QueryRepo + a YAML file (not PG) and uses only
// the standard library (no gin) to keep the desktop binary lean. The data
// plane (proxy.Router) is mounted separately; main.go routes /api/v1/* to
// this handler and everything else to the proxy.
package desktopapi

import (
	"encoding/json"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	desktopcfg "voxeltoad/cmd/desktop/config"
	"voxeltoad/internal/app"
	"voxeltoad/internal/buildinfo"
	"voxeltoad/internal/config"
	"voxeltoad/internal/desktoplog"
	"voxeltoad/internal/desktopstore"
)

// Server wires the read endpoints + config CRUD. The configPath + watcher are
// nil-safe: when zero, config endpoints return 503 (desktop started without a
// writable config, e.g. in some tests). Read endpoints always work. The logs
// ring, key state and key store are likewise optional: nil disables their
// endpoints (503).
type Server struct {
	repo       *desktopstore.QueryRepo
	prompts    *desktopstore.PromptRepo
	configPath string
	watcher    *app.DispatcherWatcher
	logs       *desktoplog.Ring
	keyState   *KeyState
	keys       *desktopstore.KeyStore
	// quitFn backs POST /api/v1/app/quit; injected via SetQuitFunc once the
	// desktop shell exists (nil → endpoint 503s).
	quitFn func()
}

// New builds the read API server over the given SQLite connection. configPath
// and watcher enable the /api/v1/{providers,models,routes} CRUD endpoints with
// hot-reload; pass empty/nil to disable them (read-only mode). logs is the
// process log ring for /api/v1/logs; keyState+keys back the API-key
// endpoints; nil disables them.
func New(db *desktopstore.DB, configPath string, watcher *app.DispatcherWatcher, logs *desktoplog.Ring, keyState *KeyState) *Server {
	return &Server{
		repo:       desktopstore.NewQueryRepo(db),
		prompts:    desktopstore.NewPromptRepo(db),
		configPath: configPath,
		watcher:    watcher,
		logs:       logs,
		keyState:   keyState,
		keys:       desktopstore.NewKeyStore(db),
	}
}

// Handler returns the HTTP handler for the API. Mount it at /api/v1/.
func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /api/v1/health", s.handleHealth)
	mux.HandleFunc("GET /api/v1/request-logs", s.handleRequestLogs)
	mux.HandleFunc("GET /api/v1/sessions", s.handleSessions)
	mux.HandleFunc("GET /api/v1/overview", s.handleOverview)
	mux.HandleFunc("GET /api/v1/trace/sessions/{session_id}", s.handleTraceBySession)
	mux.HandleFunc("GET /api/v1/trace/rows/{id}", s.handleTraceByRowID)
	// request_id values generated by the data plane contain a slash
	// (e.g. "NODE/abc-000001"), so a single-segment wildcard would 404. The
	// "..." multi-segment wildcard (Go 1.22+) captures the full remainder.
	mux.HandleFunc("GET /api/v1/trace/requests/{request_id...}", s.handleTraceByRequestID)
	mux.HandleFunc("GET /api/v1/logs", s.handleLogs)
	mux.HandleFunc("GET /api/v1/apikey", s.handleGetAPIKey)
	mux.HandleFunc("POST /api/v1/apikey/rotate", s.handleRotateAPIKey)
	// Playground needs only the dispatcher (works even in read-only mode when
	// one was injected); the handler nil-guards it.
	mux.HandleFunc("POST /api/v1/playground/chat", s.handlePlaygroundChat)

	// Prompt favorites (design/desktop.md §10.3-7) — store-backed, always on.
	mux.HandleFunc("GET /api/v1/prompts", s.handleListPrompts)
	mux.HandleFunc("POST /api/v1/prompts", s.handleCreatePrompt)
	mux.HandleFunc("GET /api/v1/prompts/{id}", s.handleGetPrompt)
	mux.HandleFunc("PUT /api/v1/prompts/{id}", s.handleUpdatePrompt)
	mux.HandleFunc("DELETE /api/v1/prompts/{id}", s.handleDeletePrompt)

	// Config CRUD (providers / models / routes) + manual reload. Disabled when
	// the server was built without a configPath/watcher (read-only mode).
	if s.configPath != "" && s.watcher != nil {
		mux.HandleFunc("GET /api/v1/providers", s.handleListProviders)
		mux.HandleFunc("POST /api/v1/providers", s.handleCreateProvider)
		mux.HandleFunc("GET /api/v1/providers/{name}", s.handleGetProvider)
		mux.HandleFunc("PUT /api/v1/providers/{name}", s.handleUpdateProvider)
		mux.HandleFunc("DELETE /api/v1/providers/{name}", s.handleDeleteProvider)

		mux.HandleFunc("GET /api/v1/models", s.handleListModels)
		mux.HandleFunc("POST /api/v1/models", s.handleCreateModel)
		mux.HandleFunc("GET /api/v1/models/{alias}", s.handleGetModel)
		mux.HandleFunc("PUT /api/v1/models/{alias}", s.handleUpdateModel)
		mux.HandleFunc("DELETE /api/v1/models/{alias}", s.handleDeleteModel)

		mux.HandleFunc("GET /api/v1/routes", s.handleListRoutes)
		mux.HandleFunc("POST /api/v1/routes", s.handleCreateRoute)
		mux.HandleFunc("GET /api/v1/routes/{alias}", s.handleGetRoute)
		mux.HandleFunc("PUT /api/v1/routes/{alias}", s.handleUpdateRoute)
		mux.HandleFunc("DELETE /api/v1/routes/{alias}", s.handleDeleteRoute)

		mux.HandleFunc("POST /api/v1/config/reload", s.handleReload)

		mux.HandleFunc("GET /api/v1/settings", s.handleGetSettings)
		mux.HandleFunc("PUT /api/v1/settings", s.handlePutSettings)
	}

	// App-control endpoints for the sidebar footer buttons (they replace the
	// native menu items, which only existed on the Windows menu bar). Both
	// register unconditionally and guard at request time — quit because
	// SetQuitFunc is called after Handler(), reveal so a config-less server
	// answers a clean JSON 503 instead of the mux's plain 404.
	mux.HandleFunc("POST /api/v1/config/reveal", s.handleConfigReveal)
	mux.HandleFunc("POST /api/v1/app/quit", s.handleAppQuit)
	return mux
}

// ---------------------------------------------------------------------------
// handlers
// ---------------------------------------------------------------------------

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	// version lets the UI (and support) tell a stale binary apart from one
	// that has the endpoints it calls — a version mismatch is the usual cause
	// of API 404s after an upgrade.
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok", "version": buildinfo.Version})
}

func (s *Server) handleRequestLogs(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	from, to, ok := parseTimeRange(w, r)
	if !ok {
		return
	}
	rows, total, err := s.repo.ListRequestLogs(r.Context(), desktopstore.RequestLogFilter{
		Provider:       q.Get("provider"),
		ModelRequested: q.Get("model_requested"),
		ErrorType:      q.Get("error_type"),
		SessionID:      q.Get("session_id"),
		RequestID:      q.Get("request_id"),
		AgentType:      q.Get("agent_type"),
		From:           from,
		To:             to,
	}, parsePage(q), parsePageSize(q))
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	writeJSON(w, http.StatusOK, offsetEnvelope(rows, total, parsePage(q), parsePageSize(q)))
}

func (s *Server) handleSessions(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	from, to, ok := parseTimeRange(w, r)
	if !ok {
		return
	}
	sessions, total, err := s.repo.ListSessions(r.Context(), desktopstore.SessionListFilter{
		AgentType: q.Get("agent_type"),
		From:      from,
		To:        to,
	}, parsePage(q), parsePageSize(q))
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	writeJSON(w, http.StatusOK, offsetEnvelope(sessions, total, parsePage(q), parsePageSize(q)))
}

func (s *Server) handleOverview(w http.ResponseWriter, r *http.Request) {
	from, to, ok := parseTimeRange(w, r)
	if !ok {
		return
	}
	agents, totals, err := s.repo.Overview(r.Context(), from, to)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"agents": agents,
		"totals": totals,
	})
}

func (s *Server) handleTraceBySession(w http.ResponseWriter, r *http.Request) {
	sessionID := r.PathValue("session_id")
	if sessionID == "" {
		writeError(w, http.StatusBadRequest, "session_id path parameter is required")
		return
	}
	rows, err := s.repo.ListTraceBySession(r.Context(), sessionID, parseLimit(r.URL.Query()))
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"session_id": sessionID,
		"requests":   rows,
	})
}

func (s *Server) handleTraceByRowID(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseInt(r.PathValue("id"), 10, 64)
	if err != nil || id <= 0 {
		writeError(w, http.StatusBadRequest, "id must be a positive integer")
		return
	}
	d, ok, err := s.repo.GetTraceByRowID(r.Context(), id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	if !ok {
		writeError(w, http.StatusNotFound, "trace not found")
		return
	}
	writeJSON(w, http.StatusOK, d)
}

func (s *Server) handleTraceByRequestID(w http.ResponseWriter, r *http.Request) {
	requestID := r.PathValue("request_id")
	if requestID == "" {
		writeError(w, http.StatusBadRequest, "request_id path parameter is required")
		return
	}
	d, ok, err := s.repo.GetTraceByRequestID(r.Context(), requestID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query failed")
		return
	}
	if !ok {
		writeError(w, http.StatusNotFound, "trace not found")
		return
	}
	writeJSON(w, http.StatusOK, d)
}

// handleLogs serves the process log ring for the UI log viewer: the newest
// `tail` lines, oldest first (the page renders newest-first itself).
func (s *Server) handleLogs(w http.ResponseWriter, r *http.Request) {
	if s.logs == nil {
		writeError(w, http.StatusServiceUnavailable, "logs not available")
		return
	}
	tail := clampInt(firstQuery(r.URL.Query(), "tail"), 1, maxLogTail, defaultLogTail)
	writeJSON(w, http.StatusOK, map[string]any{"lines": s.logs.Tail(tail)})
}

// ---------------------------------------------------------------------------
// response helpers + param parsers
// ---------------------------------------------------------------------------

// offsetEnvelope wraps a page payload for offset-paginated endpoints, mirroring
// the enterprise admin API's {data, total, page, page_size} contract so the
// reused UI components need no remapping.
func offsetEnvelope(data any, total int64, page, pageSize int) map[string]any {
	return map[string]any{
		"data":      data,
		"total":     total,
		"page":      page,
		"page_size": pageSize,
	}
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

const (
	defaultPageSize = 20
	maxPageSize     = 100
	maxPage         = 500
	defaultLimit    = 50
	maxLimit        = 500
	defaultLogTail  = 500
	maxLogTail      = 2000
)

func parsePage(q map[string][]string) int {
	return clampInt(firstQuery(q, "page"), 1, maxPage, 1)
}

func parsePageSize(q map[string][]string) int {
	return clampInt(firstQuery(q, "page_size"), 1, maxPageSize, defaultPageSize)
}

func parseLimit(q map[string][]string) int {
	return clampInt(firstQuery(q, "limit"), 1, maxLimit, defaultLimit)
}

func firstQuery(q map[string][]string, key string) string {
	if v := q[key]; len(v) > 0 {
		return v[0]
	}
	return ""
}

func clampInt(s string, lo, hi, def int) int {
	n, err := strconv.Atoi(s)
	if err != nil || n < lo {
		return def
	}
	if n > hi {
		return hi
	}
	return n
}

// parseTimeRange reads optional RFC3339 from/to query params. Absent params are
// zero times (unbounded). Malformed values → 400 and ok=false.
func parseTimeRange(w http.ResponseWriter, r *http.Request) (from, to time.Time, ok bool) {
	q := r.URL.Query()
	if s := q.Get("from"); s != "" {
		t, err := time.Parse(time.RFC3339, s)
		if err != nil {
			writeError(w, http.StatusBadRequest, "invalid from timestamp (want RFC3339)")
			return time.Time{}, time.Time{}, false
		}
		from = t
	}
	if s := q.Get("to"); s != "" {
		t, err := time.Parse(time.RFC3339, s)
		if err != nil {
			writeError(w, http.StatusBadRequest, "invalid to timestamp (want RFC3339)")
			return time.Time{}, time.Time{}, false
		}
		to = t
	}
	return from, to, true
}

// ---------------------------------------------------------------------------
// static SPA hosting
// ---------------------------------------------------------------------------

// Static serves the built desktop UI (a Vite SPA) from distDir on the same
// origin as the read API, so the app is a single binary with no separate
// frontend server. Unknown (non-asset) paths fall back to index.html for
// client-side routing. When distDir is empty or missing, a short HTML notice
// is returned so the gateway still starts and the /api/v1 read API keeps working.
//
// The data plane (/v1/*) and the read API (/api/v1/*) are routed to their
// handlers in main.go BEFORE this one, so they are never shadowed by SPA
// fallback.
func Static(distDir string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if distDir == "" {
			serveUINotBuilt(w)
			return
		}
		upath := filepath.Clean("/" + r.URL.Path)
		file := filepath.Join(distDir, upath)
		if info, err := os.Stat(file); err == nil && !info.IsDir() {
			http.ServeFile(w, r, file)
			return
		}
		// SPA history fallback: serve index.html for any non-file route.
		index := filepath.Join(distDir, "index.html")
		if _, err := os.Stat(index); err == nil {
			http.ServeFile(w, r, index)
			return
		}
		serveUINotBuilt(w)
	})
}

func serveUINotBuilt(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">
<title>桌面网关助手</title></head><body style="font-family:system-ui;max-width:640px;margin:80px auto;padding:0 20px;color:#0f172a">
<h2>桌面网关助手</h2>
<p>前��界面尚未构建。请在 <code>desktop-ui</code> 执行 <code>npm install &amp;&amp; npm run build</code>，
然后用 <code>DESKTOP_WEB_DIST</code> 指向构建产物目录（默认 <code>desktop-ui/dist</code>）。</p>
<p>数据面与 <code>/api/v1</code> 只读接口已正常工作。</p>
</body></html>`))
}

// ---------------------------------------------------------------------------
// config CRUD (providers / models / routes) — backed by the local YAML file
// ---------------------------------------------------------------------------

// configDisabled guards every config handler. Returns true (and has written the
// 503) when the server was built without a configPath/watcher.
func (s *Server) configDisabled(w http.ResponseWriter) bool {
	if s.configPath == "" || s.watcher == nil {
		writeError(w, http.StatusServiceUnavailable, "config CRUD disabled (server in read-only mode)")
		return true
	}
	return false
}

// loadConfig reads the current YAML into a Dynamic pointer. On read/parse
// failure it returns 500 (the file should have been valid at startup; a mid-run
// corruption is an operator-visible error, not a not-found).
func (s *Server) loadConfig(w http.ResponseWriter) *config.Dynamic {
	dyn, err := desktopcfg.LoadFromFile(s.configPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "read config: "+err.Error())
		return nil
	}
	return dyn
}

// saveConfigAndReload is the post-write path shared by every POST/PUT/DELETE:
// bump version (so DispatcherWatcher.rebuild sees a change) -> atomic write ->
// rebuild dispatcher (force). The write goes through SaveFile: a nil gateway
// override preserves the bootstrap `gateway:` section (listen addr + session
// headers, not modeled by config.Dynamic) as-is, while a non-nil override
// replaces it (settings-editor path) — dropping the section would silently
// move the gateway back to :12800 on the next restart. Rebuild failure is
// logged but NOT returned as an error: the file is already updated, and
// keeping the last-good dispatcher is the documented behavior
// (watcher.go:71-73). The API returns 200 with a warning field so the UI can
// surface "saved but live-reload failed".
func (s *Server) saveConfigAndReload(w http.ResponseWriter, dyn *config.Dynamic, gateway *desktopcfg.GatewaySection) (warning string, ok bool) {
	dyn.Version = "desktop-" + time.Now().UTC().Format("20060102-150405.000")
	if err := desktopcfg.SaveFile(s.configPath, dyn, gateway); err != nil {
		writeError(w, http.StatusInternalServerError, "write config: "+err.Error())
		return "", false
	}
	if err := s.watcher.Build(); err != nil {
		// Config landed on disk; the live dispatcher keeps the previous good
		// state. Surface a warning so the user knows to fix + reload.
		return "saved but hot-reload failed: " + err.Error(), true
	}
	return "", true
}

// --- providers ---

func (s *Server) handleListProviders(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	writeJSON(w, http.StatusOK, dyn.Providers)
}

func (s *Server) handleGetProvider(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	name := r.PathValue("name")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, p := range dyn.Providers {
		if p.Name == name {
			writeJSON(w, http.StatusOK, p)
			return
		}
	}
	writeError(w, http.StatusNotFound, "provider not found")
}

func (s *Server) handleCreateProvider(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	var p config.Provider
	if !readJSON(w, r, &p) {
		return
	}
	if p.Name == "" {
		writeError(w, http.StatusBadRequest, "name is required")
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, existing := range dyn.Providers {
		if existing.Name == p.Name {
			writeError(w, http.StatusConflict, "provider "+p.Name+" already exists")
			return
		}
	}
	dyn.Providers = append(dyn.Providers, p)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusCreated, envelope{Data: p, Warning: warn})
	}
}

func (s *Server) handleUpdateProvider(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	name := r.PathValue("name")
	var p config.Provider
	if !readJSON(w, r, &p) {
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	idx := -1
	for i, existing := range dyn.Providers {
		if existing.Name == name {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "provider not found")
		return
	}
	// Name in URL wins (renames via PUT are rejected to avoid breaking model/route refs).
	p.Name = name
	dyn.Providers[idx] = p
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Data: p, Warning: warn})
	}
}

func (s *Server) handleDeleteProvider(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	name := r.PathValue("name")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	// Reference check: reject if any model upstream or route references it.
	for _, m := range dyn.Models {
		for _, u := range m.Upstreams {
			if u.Provider == name {
				writeError(w, http.StatusConflict, "provider "+name+" is referenced by model "+m.Alias)
				return
			}
		}
	}
	for _, rt := range dyn.Routes {
		for _, rp := range rt.Providers {
			if rp.Name == name {
				writeError(w, http.StatusConflict, "provider "+name+" is referenced by route "+rt.ModelAlias)
				return
			}
		}
	}
	idx := -1
	for i, existing := range dyn.Providers {
		if existing.Name == name {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "provider not found")
		return
	}
	dyn.Providers = append(dyn.Providers[:idx], dyn.Providers[idx+1:]...)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Warning: warn})
	}
}

// --- models ---

func (s *Server) handleListModels(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	writeJSON(w, http.StatusOK, dyn.Models)
}

func (s *Server) handleGetModel(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, m := range dyn.Models {
		if m.Alias == alias {
			writeJSON(w, http.StatusOK, m)
			return
		}
	}
	writeError(w, http.StatusNotFound, "model not found")
}

func (s *Server) handleCreateModel(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	var m config.Model
	if !readJSON(w, r, &m) {
		return
	}
	if m.Alias == "" {
		writeError(w, http.StatusBadRequest, "alias is required")
		return
	}
	if err := validateModelUpstreams(m, s); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, existing := range dyn.Models {
		if existing.Alias == m.Alias {
			writeError(w, http.StatusConflict, "model "+m.Alias+" already exists")
			return
		}
	}
	dyn.Models = append(dyn.Models, m)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusCreated, envelope{Data: m, Warning: warn})
	}
}

func (s *Server) handleUpdateModel(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	var m config.Model
	if !readJSON(w, r, &m) {
		return
	}
	if err := validateModelUpstreams(m, s); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	idx := -1
	for i, existing := range dyn.Models {
		if existing.Alias == alias {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "model not found")
		return
	}
	m.Alias = alias
	dyn.Models[idx] = m
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Data: m, Warning: warn})
	}
}

func (s *Server) handleDeleteModel(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	// Reference check: reject if any route points at this alias.
	for _, rt := range dyn.Routes {
		if rt.ModelAlias == alias {
			writeError(w, http.StatusConflict, "model "+alias+" is referenced by route "+rt.ModelAlias)
			return
		}
	}
	idx := -1
	for i, existing := range dyn.Models {
		if existing.Alias == alias {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "model not found")
		return
	}
	dyn.Models = append(dyn.Models[:idx], dyn.Models[idx+1:]...)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Warning: warn})
	}
}

// validateModelUpstreams rejects a model whose upstreams reference an unknown
// provider (would make BuildDispatcher fail). Done at write time so the YAML
// never lands in a state the dispatcher can't build.
func validateModelUpstreams(m config.Model, s *Server) error {
	if len(m.Upstreams) == 0 {
		return errStr("model " + m.Alias + " needs at least one upstream")
	}
	dyn, err := desktopcfg.LoadFromFile(s.configPath)
	if err != nil {
		return errStr("read config to validate: " + err.Error())
	}
	known := map[string]bool{}
	for _, p := range dyn.Providers {
		known[p.Name] = true
	}
	for _, u := range m.Upstreams {
		if !known[u.Provider] {
			return errStr("upstream provider " + u.Provider + " does not exist")
		}
	}
	return nil
}

// --- routes ---

func (s *Server) handleListRoutes(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	writeJSON(w, http.StatusOK, dyn.Routes)
}

func (s *Server) handleGetRoute(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, rt := range dyn.Routes {
		if rt.ModelAlias == alias {
			writeJSON(w, http.StatusOK, rt)
			return
		}
	}
	writeError(w, http.StatusNotFound, "route not found")
}

func (s *Server) handleCreateRoute(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	var rt config.Route
	if !readJSON(w, r, &rt) {
		return
	}
	if rt.ModelAlias == "" {
		writeError(w, http.StatusBadRequest, "model_alias is required")
		return
	}
	if err := validateRouteProviders(rt, s); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	for _, existing := range dyn.Routes {
		if existing.ModelAlias == rt.ModelAlias {
			writeError(w, http.StatusConflict, "route "+rt.ModelAlias+" already exists")
			return
		}
	}
	dyn.Routes = append(dyn.Routes, rt)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusCreated, envelope{Data: rt, Warning: warn})
	}
}

func (s *Server) handleUpdateRoute(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	var rt config.Route
	if !readJSON(w, r, &rt) {
		return
	}
	if err := validateRouteProviders(rt, s); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	idx := -1
	for i, existing := range dyn.Routes {
		if existing.ModelAlias == alias {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "route not found")
		return
	}
	rt.ModelAlias = alias
	dyn.Routes[idx] = rt
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Data: rt, Warning: warn})
	}
}

func (s *Server) handleDeleteRoute(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	alias := r.PathValue("alias")
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	idx := -1
	for i, existing := range dyn.Routes {
		if existing.ModelAlias == alias {
			idx = i
			break
		}
	}
	if idx < 0 {
		writeError(w, http.StatusNotFound, "route not found")
		return
	}
	dyn.Routes = append(dyn.Routes[:idx], dyn.Routes[idx+1:]...)
	if warn, ok := s.saveConfigAndReload(w, dyn, nil); ok {
		writeJSON(w, http.StatusOK, envelope{Warning: warn})
	}
}

func validateRouteProviders(rt config.Route, s *Server) error {
	if len(rt.Providers) == 0 {
		return errStr("route " + rt.ModelAlias + " needs at least one provider")
	}
	dyn, err := desktopcfg.LoadFromFile(s.configPath)
	if err != nil {
		return errStr("read config to validate: " + err.Error())
	}
	known := map[string]bool{}
	for _, p := range dyn.Providers {
		known[p.Name] = true
	}
	for _, rp := range rt.Providers {
		if !known[rp.Name] {
			return errStr("route provider " + rp.Name + " does not exist")
		}
	}
	return nil
}

// --- manual reload ---

func (s *Server) handleReload(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	if err := s.watcher.Build(); err != nil {
		writeError(w, http.StatusUnprocessableEntity, "reload failed: "+err.Error())
		return
	}
	writeJSON(w, http.StatusOK, envelope{Data: map[string]string{"status": "reloaded"}})
}

// --- gateway settings (settings page) ---

// settingsView is the GET/PUT payload for /api/v1/settings: the editable
// subset of the desktop YAML — bootstrap gateway section (listen addr +
// session headers, restart-applied) plus the hot-reloadable trace capture
// knobs.
type settingsView struct {
	Gateway gatewaySettingsView `json:"gateway"`
	Trace   traceSettingsView   `json:"trace"`
}

type gatewaySettingsView struct {
	Addr           string   `json:"addr"`
	SessionHeaders []string `json:"session_headers"`
}

type traceSettingsView struct {
	CapturePayloadEnabled bool `json:"capture_payload_enabled"`
	MaxBodyKB             int  `json:"max_body_kb"`
	RetentionDays         int  `json:"retention_days"`
}

func (s *Server) handleGetSettings(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	gw, err := desktopcfg.LoadGatewaySection(s.configPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "read gateway section: "+err.Error())
		return
	}
	v := settingsView{Gateway: gatewaySettingsView{Addr: gw.Addr, SessionHeaders: gw.SessionHeaders}}
	if dyn.Settings != nil {
		v.Trace = traceSettingsView{
			CapturePayloadEnabled: dyn.Settings.Trace.CapturePayloadEnabled,
			MaxBodyKB:             dyn.Settings.Trace.MaxBodyKB,
			RetentionDays:         dyn.Settings.Trace.RetentionDays,
		}
	}
	writeJSON(w, http.StatusOK, v)
}

func (s *Server) handlePutSettings(w http.ResponseWriter, r *http.Request) {
	if s.configDisabled(w) {
		return
	}
	var v settingsView
	if !readJSON(w, r, &v) {
		return
	}
	if err := validateSettings(v); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dyn := s.loadConfig(w)
	if dyn == nil {
		return
	}
	dyn.Settings = &config.GatewaySettings{
		Trace: config.TraceSettings{
			CapturePayloadEnabled: v.Trace.CapturePayloadEnabled,
			MaxBodyKB:             v.Trace.MaxBodyKB,
			RetentionDays:         v.Trace.RetentionDays,
		},
	}
	gw := &desktopcfg.GatewaySection{Addr: v.Gateway.Addr, SessionHeaders: v.Gateway.SessionHeaders}
	// The trace knobs hot-apply via the dispatcher rebuild below; addr and
	// session headers are bootstrap-only and land on the next process start.
	// Say so in the warning so the UI can set expectations honestly.
	if warn, ok := s.saveConfigAndReload(w, dyn, gw); ok {
		msg := "trace 设置已即时生效；监听地址与会话头将在重启后生效"
		if warn != "" {
			msg = warn + "；" + msg
		}
		writeJSON(w, http.StatusOK, envelope{Data: v, Warning: msg})
	}
}

// validateSettings enforces the minimal invariants that keep the gateway
// bootable: a parseable host:port listen address, well-formed session header
// names, and non-negative trace knobs.
func validateSettings(v settingsView) error {
	if v.Gateway.Addr == "" {
		return errStr("gateway.addr is required")
	}
	if _, port, err := net.SplitHostPort(v.Gateway.Addr); err != nil || port == "" {
		return errStr("gateway.addr must be host:port (e.g. 127.0.0.1:8787)")
	}
	for _, h := range v.Gateway.SessionHeaders {
		if h == "" || strings.ContainsAny(h, " \t\r\n:") {
			return errStr("session header names must be non-empty and contain no whitespace or colon")
		}
	}
	if v.Trace.MaxBodyKB < 0 {
		return errStr("trace.max_body_kb must be >= 0")
	}
	if v.Trace.RetentionDays < 0 {
		return errStr("trace.retention_days must be >= 0")
	}
	return nil
}

// ---------------------------------------------------------------------------
// small helpers used by the config handlers
// ---------------------------------------------------------------------------

type envelope struct {
	Data    any    `json:"data"`
	Warning string `json:"warning,omitempty"`
}

type errStr string

func (e errStr) Error() string { return string(e) }

// readJSON decodes r.Body into v. On error it writes a 400 and returns false.
func readJSON(w http.ResponseWriter, r *http.Request, v any) bool {
	defer r.Body.Close()
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return false
	}
	return true
}
