-- +goose Up
-- +goose StatementBegin

-- Per-request audit ledger for the DATA PLANE (distinct from audit_logs, which
-- records management-plane config mutations). Every LLM request — success or
-- rejection — appends one row here. This is a business/compliance ledger: it is
-- written 100% (not sampled, unlike trace/metric telemetry which is exported to
-- an external backend and never stored locally). Identities are denormalized
-- strings (tenant/group names, public api_key_id), matching usage_records
-- (ADR-0014). Written off the hot path by a fail-open async recorder (ADR-0016).
CREATE TABLE request_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant            VARCHAR NOT NULL DEFAULT '',
    group_name        VARCHAR NOT NULL DEFAULT '',
    api_key_id        VARCHAR NOT NULL DEFAULT '',
    provider          VARCHAR NOT NULL DEFAULT '',
    model_requested   VARCHAR NOT NULL DEFAULT '',
    model_resolved    VARCHAR NOT NULL DEFAULT '',
    stream            BOOLEAN NOT NULL DEFAULT false,
    prompt_tokens     INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens      INTEGER NOT NULL DEFAULT 0,
    ttft_ms           INTEGER NOT NULL DEFAULT 0,
    duration_ms       INTEGER NOT NULL DEFAULT 0,
    error_type        VARCHAR NOT NULL DEFAULT '',
    blocked_by        VARCHAR NOT NULL DEFAULT '',
    fallback          BOOLEAN NOT NULL DEFAULT false,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- DEFAULT partition catches all rows so phase-1 inserts work without per-month
-- partition management; ops/phase-2 may add monthly partitions later (mirrors
-- usage_records).
CREATE TABLE request_logs_default PARTITION OF request_logs DEFAULT;

-- Index backing time-range and per-tenant queries of the request feed.
CREATE INDEX idx_request_logs_created_at ON request_logs (created_at);
CREATE INDEX idx_request_logs_tenant_created ON request_logs (tenant, created_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS request_logs;
-- +goose StatementEnd
