-- +goose Up
-- +goose StatementBegin

-- Snapshot-version counter (ADR-0015): a single row bumped in the same
-- transaction as any config write; read as the snapshot ETag.
CREATE TABLE config_generation (
    version BIGINT NOT NULL
);
INSERT INTO config_generation (version) VALUES (0);

-- Platform-level config (ADR-0014 §3: global, super-admin managed). Identity
-- columns are promoted for querying/constraints; leaf detail lives in spec/params
-- JSONB and serializes verbatim into the config snapshot.
CREATE TABLE providers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR NOT NULL UNIQUE,
    type       VARCHAR NOT NULL,
    adapter    VARCHAR NOT NULL,
    enabled    BOOLEAN NOT NULL DEFAULT true,
    spec       JSONB   NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE models (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias      VARCHAR NOT NULL UNIQUE,
    enabled    BOOLEAN NOT NULL DEFAULT true,
    spec       JSONB   NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE routes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_alias VARCHAR NOT NULL UNIQUE,
    strategy    VARCHAR NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT true,
    spec        JSONB   NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE plugins (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR NOT NULL,
    phase      VARCHAR NOT NULL,
    scope      VARCHAR NOT NULL DEFAULT '',
    enabled    BOOLEAN NOT NULL DEFAULT true,
    spec       JSONB   NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tenancy (ADR-0005): Tenant -> Group -> APIKey.
CREATE TABLE tenants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR NOT NULL UNIQUE,
    enabled    BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL REFERENCES tenants (id),
    name       VARCHAR NOT NULL,
    enabled    BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

-- API keys: hashed (SHA-256 hex) lookup key, public key_id, soft-delete via
-- revoked_at preserving revocation history and audit-time key_id resolution
-- (ADR-0006/0014).
CREATE TABLE api_keys (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id         VARCHAR NOT NULL UNIQUE,
    hash           CHAR(64) NOT NULL UNIQUE,
    tenant_id      BIGINT NOT NULL REFERENCES tenants (id),
    group_id       BIGINT REFERENCES groups (id),
    expires_at     TIMESTAMPTZ,
    allowed_models JSONB NOT NULL DEFAULT '[]',
    revoked_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Quota balances keyed by the hierarchical scope string the auth record
-- produces (ADR-0014 §2). Money is BIGINT micro-units (ADR-0013). The data-plane
-- debit is a single atomic conditional UPDATE on the scope PK.
CREATE TABLE quotas (
    scope      VARCHAR PRIMARY KEY,
    balance    BIGINT NOT NULL,
    currency   VARCHAR NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Usage records (audit/reconciliation), month range-partitioned from day one
-- (ADR-0014). The partition key (created_at) must be part of the primary key.
-- cost is BIGINT micro-units (ADR-0013). Identities are DENORMALIZED strings
-- (tenant/group names, public api_key_id) — the data plane only ever has these
-- (ADR-0006), and an append-only audit row should preserve identity as-it-was,
-- independent of later renames/deletes. No FK into api_keys.
CREATE TABLE usage_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant            VARCHAR NOT NULL,
    group_name        VARCHAR NOT NULL DEFAULT '',
    api_key_id        VARCHAR NOT NULL,
    provider          VARCHAR NOT NULL,
    model             VARCHAR NOT NULL,
    prompt_tokens     INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    cost              BIGINT  NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- DEFAULT partition catches all rows so phase-1 inserts work without per-month
-- partition management; ops/phase-2 may add monthly partitions later.
CREATE TABLE usage_records_default PARTITION OF usage_records DEFAULT;

CREATE INDEX idx_usage_records_created_at ON usage_records (created_at);
CREATE INDEX idx_usage_records_tenant_created ON usage_records (tenant, created_at);

-- Audit log (ADR-0017): append-only, populated once RBAC supplies operator_id;
-- excluded from the config snapshot.
CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id   BIGINT,
    action        VARCHAR NOT NULL,
    resource_type VARCHAR NOT NULL,
    resource_id   VARCHAR NOT NULL,
    before        JSONB,
    after         JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS usage_records;
DROP TABLE IF EXISTS quotas;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS plugins;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS config_generation;
-- +goose StatementEnd
