-- +goose Up
-- +goose StatementBegin

-- Management-plane operators (ADR-0017). Distinct system from client API keys
-- (ADR-0006): human operators authenticate with email + argon2id password hash.
-- role is a small enum (super-admin/tenant-admin) — a separate roles table is a
-- phase-2 concern. tenant_id is NULL for super-admin (global) and set for a
-- tenant-admin (bound to one tenant).
CREATE TABLE operators (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    role          VARCHAR NOT NULL CHECK (role IN ('super-admin', 'tenant-admin')),
    tenant_id     BIGINT REFERENCES tenants (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- super-admin is global (no tenant); tenant-admin must be bound to one.
    CONSTRAINT operator_role_tenant CHECK (
        (role = 'super-admin' AND tenant_id IS NULL) OR
        (role = 'tenant-admin' AND tenant_id IS NOT NULL)
    )
);

-- Server-side sessions (ADR-0017): opaque token, revocable instantly (firing an
-- operator or logout deletes their sessions). Preferred over stateless JWT so
-- revocation needs no denylist.
CREATE TABLE sessions (
    token       VARCHAR PRIMARY KEY,
    operator_id BIGINT NOT NULL REFERENCES operators (id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sessions_operator ON sessions (operator_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS operators;
-- +goose StatementEnd
