-- +goose Up
-- +goose StatementBegin

-- RBAC roles: a named set of permissions + a scope_kind that determines whether
-- the operator acts globally (tenant_id IS NULL) or within a tenant
-- (tenant_id IS NOT NULL). This is the data model envisioned by ADR-0017 §1.

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL UNIQUE,
    scope_kind  VARCHAR NOT NULL CHECK (scope_kind IN ('global', 'tenant')),
    is_builtin  BOOLEAN NOT NULL DEFAULT false,
    description VARCHAR NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE role_permissions (
    role_id    BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission VARCHAR NOT NULL,
    PRIMARY KEY (role_id, permission)
);

-- Seed the two built-in roles (ADR-0017 §1). super-admin carries the wildcard
-- sentinel "*" which means "all permissions". tenant-admin carries the tenant-
-- scoped and both-scoped permission set.

INSERT INTO roles (name, scope_kind, is_builtin, description) VALUES
    ('super-admin', 'global', true, 'Built-in global administrator with all permissions'),
    ('tenant-admin', 'tenant', true, 'Built-in tenant administrator');

-- super-admin: wildcard (all permissions)
INSERT INTO role_permissions (role_id, permission)
    SELECT id, '*' FROM roles WHERE name = 'super-admin';

-- tenant-admin: tenant-scoped crud + both-scoped reads + self-service
INSERT INTO role_permissions (role_id, permission)
    SELECT r.id, p.permission
    FROM roles r, (VALUES
        ('api_key.read'), ('api_key.write'),
        ('group.read'), ('group.write'),
        ('usage.read'), ('audit.read'), ('request_log.read'),
        ('quota.read'), ('password.write')
    ) AS p(permission)
    WHERE r.name = 'tenant-admin';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS roles;

-- +goose StatementEnd
