-- +goose Up
-- +goose StatementBegin

-- LLM trace payload ledger — the message + raw layers below request_logs
-- (ADR-0039). Where request_logs stores ONLY non-sensitive metadata per request,
-- trace_payloads stores the prompt/completion plaintext and the raw upstream
-- request/response bodies. The two ledgers are separate by design (ADR-0039 §1):
-- different sensitivity, volume, retention, and access policy. They join 1:1 on
-- request_id at read time.
--
-- Capture is opt-in (trace.capture_payload.enabled, default off) and written
-- fail-open async off the request path (ADR-0016). Retention is short and
-- enforced by dropping monthly partitions (Phase 4).
--
-- Mirrors request_logs/usage_records: RANGE-partitioned by created_at with a
-- DEFAULT partition so phase-1 inserts work without per-month partition
-- management; identities are denormalized strings (ADR-0014).
CREATE TABLE trace_payloads (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id      VARCHAR NOT NULL DEFAULT '',
    session_id      VARCHAR NOT NULL DEFAULT '',
    trace_id        VARCHAR NOT NULL DEFAULT '',
    tenant          VARCHAR NOT NULL DEFAULT '',
    group_name      VARCHAR NOT NULL DEFAULT '',
    api_key_id      VARCHAR NOT NULL DEFAULT '',
    provider        VARCHAR NOT NULL DEFAULT '',
    model_requested VARCHAR NOT NULL DEFAULT '',
    stream          BOOLEAN NOT NULL DEFAULT false,
    -- Summary dimensions surfaced per event (mirror reference trace systems) so
    -- the request-list view can render a row WITHOUT decoding the large JSONB.
    status_code     INTEGER NOT NULL DEFAULT 0,
    stop_reason     VARCHAR NOT NULL DEFAULT '',
    n_messages      INTEGER NOT NULL DEFAULT 0,
    n_tool_use      INTEGER NOT NULL DEFAULT 0,
    -- The 4-layer model's bottom two layers. JSONB adapts to heterogeneous
    -- provider schemas; TOAST compresses the bodies for short retention.
    messages        JSONB   NOT NULL DEFAULT '[]',  -- normalized adapter.Message[]
    request_raw     JSONB   NOT NULL DEFAULT '{}',  -- original client request body
    response_raw    JSONB   NOT NULL DEFAULT '{}',  -- upstream response (reassembled for streams)
    error_raw       TEXT    NOT NULL DEFAULT '',    -- upstream error body on failure
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- DEFAULT partition catches all rows so phase-1 inserts work without per-month
-- partition management; ops/phase-2/4 may add monthly partitions + DROP-based TTL
-- later (mirrors request_logs/usage_records, ADR-0029).
CREATE TABLE trace_payloads_default PARTITION OF trace_payloads DEFAULT;

-- request_id join key to request_logs (1:1). session_id/tenant drive the
-- session-trace and tenant-scoped list queries.
CREATE INDEX idx_trace_payloads_request_id     ON trace_payloads (request_id);
CREATE INDEX idx_trace_payloads_session_created ON trace_payloads (session_id, created_at);
CREATE INDEX idx_trace_payloads_tenant_created  ON trace_payloads (tenant, created_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS trace_payloads;
-- +goose StatementEnd
