-- +goose Up
-- +goose StatementBegin

-- ADR-0051: Application as a first-class tenant-scoped governance identity.
-- An Application represents a long-lived business system consuming AI; it has
-- exactly one owning Group but may be consumed by API keys across multiple
-- Groups in the same Tenant. Disabling an Application rejects all bound keys
-- (enforced in KeyRepo.LookupByHash, not via cascading writes — mirrors the
-- disabled-tenant pattern). api_keys.application_id is nullable for migration:
-- unbound keys are measurable migration debt, not a supported long-term mode.
CREATE TABLE applications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL REFERENCES tenants (id),
    name           VARCHAR NOT NULL,
    owner_group_id BIGINT NOT NULL REFERENCES groups (id),
    enabled        BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

-- API key binding (ADR-0051 §"Application identity is derived from trusted
-- credentials"): at most one Application per key. environment is a controlled
-- credential attribute (dev/staging/prod/''), snapshotted into request/usage
-- ledgers in E0.4.
ALTER TABLE api_keys ADD COLUMN application_id BIGINT REFERENCES applications (id);
ALTER TABLE api_keys ADD COLUMN environment    VARCHAR NOT NULL DEFAULT '';

-- Backs the orphan-key scan and per-application key lists.
CREATE INDEX idx_api_keys_tenant_application
    ON api_keys (tenant_id, application_id) WHERE revoked_at IS NULL;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_api_keys_tenant_application;
ALTER TABLE api_keys DROP COLUMN IF EXISTS environment;
ALTER TABLE api_keys DROP COLUMN IF EXISTS application_id;
DROP TABLE IF EXISTS applications;
-- +goose StatementEnd
