-- +goose Up
-- +goose StatementBegin
CREATE TABLE budget_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    name TEXT NOT NULL,
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('tenant','group','application','application_env','key')),
    scope_ref TEXT NOT NULL DEFAULT '',
    environment TEXT NOT NULL DEFAULT '',
    period TEXT NOT NULL CHECK (period IN ('daily','weekly','monthly')),
    timezone TEXT NOT NULL DEFAULT 'UTC',
    currency TEXT NOT NULL CHECK (currency ~ '^[a-z]{3}$'),
    limit_amount BIGINT NOT NULL CHECK (limit_amount >= 0),
    mode TEXT NOT NULL CHECK (mode IN ('soft','enforce')),
    thresholds JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(thresholds) = 'array'),
    enabled BOOLEAN NOT NULL DEFAULT true,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_budget_policies_tenant ON budget_policies(tenant_id,id);
CREATE INDEX idx_budget_policies_match ON budget_policies(tenant_id,scope_kind,scope_ref) WHERE enabled;

CREATE TABLE budget_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES budget_policies(id),
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL CHECK (period_end > period_start),
    currency TEXT NOT NULL,
    limit_amount BIGINT NOT NULL CHECK (limit_amount >= 0),
    reserved BIGINT NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    committed BIGINT NOT NULL DEFAULT 0 CHECK (committed >= 0),
    released BIGINT NOT NULL DEFAULT 0 CHECK (released >= 0),
    UNIQUE (policy_id,period_start)
);

CREATE TABLE billing_reservations (
    id TEXT PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    request_id TEXT NOT NULL,
    -- Immutable authenticated identity, currency, estimate and price snapshot.
    identity JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('reserved','dispatched','unknown','settled','released','released_unknown')),
    actual BIGINT CHECK (actual >= 0),
    reason TEXT NOT NULL DEFAULT '',
    version BIGINT NOT NULL DEFAULT 1,
    -- Durable known result, including Usage; independent of async usage_records.
    result JSONB,
    result_applied BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_billing_reservations_tenant ON billing_reservations(tenant_id,id);
CREATE INDEX idx_billing_reservations_stale ON billing_reservations(updated_at) WHERE status IN ('reserved','dispatched');
CREATE INDEX idx_billing_reservations_pending ON billing_reservations(updated_at) WHERE result IS NOT NULL AND NOT result_applied;

CREATE TABLE billing_reservation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id TEXT NOT NULL REFERENCES billing_reservations(id),
    quota_scope TEXT,
    account_id BIGINT REFERENCES budget_accounts(id),
    reserved BIGINT NOT NULL CHECK (reserved >= 0),
    held BIGINT NOT NULL CHECK (held >= 0),
    committed BIGINT NOT NULL DEFAULT 0 CHECK (committed >= 0),
    released BIGINT NOT NULL DEFAULT 0 CHECK (released >= 0),
    CHECK ((quota_scope IS NULL) <> (account_id IS NULL)),
    UNIQUE (reservation_id,quota_scope),
    UNIQUE (reservation_id,account_id)
);

CREATE TABLE budget_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    account_id BIGINT REFERENCES budget_accounts(id),
    reservation_id TEXT REFERENCES billing_reservations(id),
    kind TEXT NOT NULL,
    threshold INTEGER NOT NULL DEFAULT 0 CHECK (threshold BETWEEN 0 AND 100),
    amount BIGINT NOT NULL DEFAULT 0,
    operator_id BIGINT,
    reason TEXT NOT NULL DEFAULT '',
    evidence TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_budget_events_tenant ON budget_events(tenant_id,id);
CREATE UNIQUE INDEX idx_budget_events_threshold ON budget_events(account_id,kind,threshold)
    WHERE account_id IS NOT NULL AND kind IN ('threshold','overspend');
CREATE UNIQUE INDEX idx_budget_events_unknown ON budget_events(reservation_id,kind) WHERE kind = 'unknown';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE budget_events;
DROP TABLE billing_reservation_items;
DROP TABLE billing_reservations;
DROP TABLE budget_accounts;
DROP TABLE budget_policies;
-- +goose StatementEnd
