#!/usr/bin/env bash
# Start the voxeltoad DATA PLANE against a running `make start-stack`.
#
# `make start-stack` brings up the management plane (adminstack on
# 127.0.0.1:8090 + an embedded PostgreSQL on a RANDOM port) and the web UI.
# It does NOT start the data plane. This script starts the data plane
# (cmd/gateway) so that configuration you change in the UI is hot-reloaded
# by the gateway, and requests to the OpenAI-compatible API (:12800) flow
# through to upstream providers — without disturbing the running stack.
#
#   make start-gateway         # from the repo root
#   ./scripts/start-gateway.sh # same
#
# Prerequisites: `make start-stack` must already be running in another
# terminal (we read adminstack's embedded-PG DSN out of its log and poll its
# /healthz). Ctrl-C stops ONLY the gateway; admin + web keep running.
#
# This is a LOCAL DEV convenience: it sets GATEWAY_ALLOW_INSECURE_DEV=1 (to bypass
# the required internal-token check, which adminstack also leaves empty) and
# reproduces adminstack's fixed dev KEK so db:// provider credentials the admin
# wrote can be decrypted by the gateway. Do NOT use this in production.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Admin plane defaults — must match cmd/adminstack/main.go + scripts/start-stack.sh.
ADMIN_URL="${ADMIN_URL:-http://127.0.0.1:8090}"
ADMINSTACK_LOG="${ADMINSTACK_LOG:-/tmp/start-stack-adminstack.log}"

# adminstack logs the DSN it boots embedded PG with (cmd/adminstack/main.go:74).
DSN_REGEX='postgres://postgres:postgres@localhost:[0-9]+/voxeltoad_adminstack\?sslmode=disable'

# Same fixed dev KEK adminstack uses to encrypt db:// provider credentials
# (cmd/adminstack/main.go:89): sha256("adminstack-dev-provider-credential-kek").
# The gateway resolves the KEK via credential.DecodeBase64Key (base64 of 32
# raw bytes), so we base64-encode the same digest here.
KEK_SEED="adminstack-dev-provider-credential-kek"

# Data-plane listen address; defaults to :12800 (config.Default).
GATEWAY_ADDR="${GATEWAY_ADDR:-:12800}"
# Snapshot poll interval (Go duration string).
POLL_INTERVAL="${POLL_INTERVAL:-5s}"

red()   { printf '\033[1;31m%s\033[0m' "$1"; }
green() { printf '\033[1;32m%s\033[0m' "$1"; }

CFG_FILE=""

cleanup() {
  [ -n "$CFG_FILE" ] && rm -f "$CFG_FILE" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# ---------------------------------------------------------------------------
# 1. adminstack must be up (it owns PG + serves the config snapshot)
# ---------------------------------------------------------------------------
if ! curl -sS -o /dev/null -m 2 "$ADMIN_URL/healthz" 2>/dev/null; then
  echo "$(red 'start-gateway: admin plane not reachable at') $ADMIN_URL"
  echo "  → start the stack first in another terminal:"
  echo "      make start-stack"
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. Recover adminstack's embedded-PG DSN from its log (port is random)
# ---------------------------------------------------------------------------
if [ ! -f "$ADMINSTACK_LOG" ]; then
  echo "$(red "start-gateway: adminstack log not found at") $ADMINSTACK_LOG"
  echo "  → is \`make start-stack\` running? (it writes the adminstack log there)"
  exit 1
fi
DSN="$(grep -aoE "$DSN_REGEX" "$ADMINSTACK_LOG" | tail -n1 || true)"
# Validate the recovered value actually looks like a postgres URL. The adminstack
# log can contain NUL/binary bytes (Postgres logs), which makes `grep` emit
# "Binary file ... matches" instead of the match unless -a is passed; a stale or
# partially-written log could still yield a garbage string, so guard explicitly.
case "$DSN" in
  postgres://*) ;;
  *)
    echo "$(red 'start-gateway: could not find adminstack PG DSN in') $ADMINSTACK_LOG"
    echo "  → the log may be stale or binary. Restart \`make start-stack\`, then retry."
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# 3. Reproduce adminstack's dev KEK as base64 (matches DecodeBase64Key)
# ---------------------------------------------------------------------------
if ! command -v openssl >/dev/null 2>&1; then
  echo "$(red 'start-gateway: openssl not found') (needed to derive the dev KEK)"
  exit 1
fi
KEK_B64="$(printf '%s' "$KEK_SEED" | openssl dgst -sha256 -binary | base64)"
if [ -z "$KEK_B64" ]; then
  echo "$(red 'start-gateway: failed to derive KEK')"
  exit 1
fi

# ---------------------------------------------------------------------------
# 4. Generate a temporary bootstrap config pointing at adminstack's PG + admin
# ---------------------------------------------------------------------------
CFG_FILE="$(mktemp -t voxeltoad-gateway-config.XXXXXX.yaml)"
cat >"$CFG_FILE" <<YAML
# Auto-generated by scripts/start-gateway.sh — do not commit.
# Targets the running \`make start-stack\`: adminstack's embedded PG (DSN below,
# port recovered from its log) and admin plane at $ADMIN_URL.

gateway:
  addr: "$GATEWAY_ADDR"
  provider_credential_kek_ref: "env://GATEWAY_PROVIDER_CREDENTIAL_KEK"

snapshot:
  admin_url: "$ADMIN_URL"
  poll_interval: $POLL_INTERVAL
  # No internal_token_ref: adminstack leaves the snapshot gate open
  # (requireInternalToken disables when token is empty). Combined with
  # GATEWAY_ALLOW_INSECURE_DEV=1 below, startup validation passes.

db:
  dsn: "$DSN"

otel:
  enabled: false
  service_name: "voxeltoad"
  endpoint: ""
YAML

# ---------------------------------------------------------------------------
# 5. Foreground: the data plane. Hot-reloads config from the admin plane.
# ---------------------------------------------------------------------------
echo "  $(green "ok") admin reachable → $ADMIN_URL"
echo "  $(green "ok") PG recovered    → $DSN"
echo
# GATEWAY_ADDR like ":12800" → "http://127.0.0.1:12800"; if it already has a
# host, strip nothing.
ADDR_PORT="${GATEWAY_ADDR##*:}"
echo "  data plane   → http://127.0.0.1:${ADDR_PORT}"
echo "  admin API    → $ADMIN_URL"
echo "  web UI       → http://localhost:3000"
echo
echo "  $(green "Ctrl-C stops ONLY the gateway") — admin + web keep running."
echo "  Local dev: GATEWAY_ALLOW_INSECURE_DEV=1, KEK = adminstack dev key."
echo

cd "$ROOT"
env \
  GATEWAY_ALLOW_INSECURE_DEV=1 \
  GATEWAY_PROVIDER_CREDENTIAL_KEK="$KEK_B64" \
  GATEWAY_CONFIG="$CFG_FILE" \
  GATEWAY_LOG_FORMAT=text \
  go run ./cmd/gateway
